import { test, expect } from '../support/fixtures'

test('839px drawer returns to the desktop sidebar at 840px with a fine pointer', async ({ page, setToken }) => {
  await setToken()
  const toggle = page.getByRole('button', { name: 'ファイル一覧', exact: true })
  expect(await page.evaluate(() => matchMedia('(pointer: fine)').matches)).toBe(true)
  await expect(toggle).toBeVisible()
  await expect(page.locator('.sidebar')).toHaveCSS('position', 'fixed')
  await toggle.click()
  await expect(page.locator('.sidebar')).toBeFocused()
  await page.setViewportSize({ width: 840, height: 900 })
  await expect(toggle).toBeHidden()
  await expect(page.locator('.sidebar')).toHaveCSS('position', 'static')
  await expect(page.locator('.sidebar')).toHaveCSS('width', '280px')
  await expect(page.locator('.sidebar')).not.toHaveAttribute('role', 'dialog')
  await expect(page.locator('.main')).not.toHaveAttribute('inert')
  await page.setViewportSize({ width: 839, height: 900 })
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await toggle.click()
  await page.keyboard.press('Escape')
  await expect(toggle).toBeFocused()
  await page.locator('.header-menu-toggle').click()
  await expect(page.locator('.header-actions')).toBeFocused()
  await page.setViewportSize({ width: 840, height: 900 })
  await expect(page.locator('.header-actions')).toHaveCSS('display', 'contents')
  await expect(page.locator('.header-menu-toggle')).toBeHidden()
  await expect(page.locator('.main')).not.toHaveAttribute('inert')
  await page.locator('.project').click()
  await page.locator('.switcher-menu').hover()
  await page.locator('.round-chip').hover()
  await expect(page.locator('.switcher-menu')).toHaveCount(0)
})
